### ISSUE TITLE
Older GPUs

### ISSUE THREAD

**Issue by ThatOneToast** [ich777/unraid-nvidia-driver#2]
This really isn't an issue, but people like my self have older GPUs such as a GTX 680. Now I can't seem to find a way to install drivers for this device, because you only support newer GPUs with the new drivers.

I don't think you have to implement them all, but you could add a section for **custom Drivers upload**. So we could go out and find my driver version of 310 and upload it my self, instead of using ones built into the application.

This is just a thought, but could help not only my self but a lot of other people with old GPUs doing nothing, but they could be useful with plex, and others.

**Comment by ich777** [comment]
@ToastArgumentative thank you for reaching out to me.
May I ask on what Unraid version are you?

I compile the now "legacy" driver v470.94 for every new Unraid version too (as long as the compiling doesn't fails), but I think your issue might be that it doesn't displays it on 6.9.2 because I only show the last 8 available drivers on the plugin page.
If you look [here](https://github.com/ich777/unraid-nvidia-driver/releases/tag/5.10.28-Unraid) you can see that the driver is still available for 6.9.2 but it isn't displayed because there are now so many driver versions available for 6.9.2

You can also see [here](https://github.com/ich777/unraid-nvidia-driver/releases/tag/5.15.30-Unraid) that the driver v470.94 is available for 6.10.0-rc4

You can always edit the configuration file so that it pulls the right driver version (v470.94) for your card with this line:

`sed -i '/driver_version=/c\driver_version=470.94' "/boot/config/plugins/nvidia-driver/settings.cfg"`

After that go to the Nvidia Driver plugin page (don't worry it will display no driver selected), click the Download button and reboot your server, everything should now work as previously...

(I know this is not the most elegant way but for 6.9.2 it is necessary because there are now so many driver versions available and I really don't want to create a "Legacy Driver" radio button on the plugin page)

As said, as long as the driver v470.94 are compiling fine with the newer Kernel versions I will continue to compile them (you can see that your card is supported [here](https://www.nvidia.com/Download/driverResults.aspx/184163/en-us) when you click on the tab "Supported Products").


> So we could go out and find my driver version of 310 and upload it my self, instead of using ones built into the application.

In instance for this driver version it is not a viable option because this driver is for way older cards and won't work with Plex anyways because first of all most of these older cards doesn't have NVENC built in and the second thing is that the container additions to the driver wont work with this driver version.

**Comment by ThatOneToast** [comment]
I am on the newest unraid version 6.9.2, I can look into this with that command supplied to me, it's not only for plex, if it's at all possible I do want to use this card for a vm on display out, as this server sits behind my tv and would like to try and jimmy a way for android tv. 

I can understand with all the GPU driver, I'm just not to tech savvy with the unraid and Linux eco system. 

But I will try and use that command, with my driver file that I have installed for my card, and if it's needed I will buy a new card. 

Thanks for the input!

**Comment by ich777** [comment]
Wait!

You want to use that card for Docker containers and as a Display output?
If yes, that is not possible, please read the first page and the headline from the [support page on the Unraid forums](https://forums.unraid.net/topic/98978-plugin-nvidia-driver/).
You can only use the card for a VM **or** for Docker containers, not both at the same time, this can cause crashes and other various unexpected behavious.

The command does nothing else than simply change the driver version to v470.94 in the configuration file for the plugin itself so that it knows that it should use another driver version.

If you are really looking into buying a new card, watch out for a Nvidia T400 or something similar, this card is only allowed to pull around 35W, doesn't need a extra power connector and you can get them brand new for about 135,-
This card should get you covered when you only have a few Plex transcodes.

Can this issue be closed now, I think the better place is the [Unraid forums](https://forums.unraid.net/) to carry this conversation on.

**Comment by ThatOneToast** [comment]
Yes it can be, I now know how to get the drivers, any other issues are now out of your hands. Thank you!
