### ISSUE TITLE
With custom Unraid Kernels

### ISSUE THREAD

**Issue by BGameiro2000** [ich777/unraid-nvidia-driver#5]
Is there any possibility of having the plugin running with custom kernels for Unraid such as [these](https://github.com/thor2002ro/unraid_kernel/releases)?
The plugin seems to be tied to the kernel version.

Currently, Unraid uses kernel 6.1, but support for Intel dGPUs was added in 6.2.
Having a common platform to use Nvidia and Intel GPUs could be useful.
Personally, I have dockers where I develop code using SYCL and it would be useful to use GPUs from each vendor in the same platform for comparison.

Guide on changing kernels: https://www.reddit.com/r/unRAID/comments/171hzau/using_an_intel_arc_a380_with_plex_and_tdarr/

If it is out of scope feel free to close it, LimeTech will eventually update the kernel but it's probably in a couple of months.

**Comment by ich777** [comment]
> Is there any possibility of having the plugin running with custom kernels for Unraid such as [these](https://github.com/thor2002ro/unraid_kernel/releases)?

Yes and no but the answer is way more complicated.



> The plugin seems to be tied to the kernel version.

Yes, but that is because on Linux the driver is always (or at least most of the times) tied to the Kernel version and my build toolchain builds/uploads the driver if it detects that a new unRAID version with a newer or different Kernel version was released.
However you could look over into the [Releases](https://github.com/ich777/unraid-nvidia-driver/releases) section and see for what Kernel versions the drivers are available.


> Currently, Unraid uses kernel 6.1, but support for Intel dGPUs was added in 6.2.

Maybe you'll find a Kernel version in the Releases section from the Nvidia driver that is the same as in the repository that you've linked, install that Kernel, boot your server with that version and then install the Nvidia driver as usual from the CA App.
But wait there is maybe a catch: I also have to say that I've never tried that and it is possible that you run into issues with the Nvidia driver because I don't know how the maintainer of that Kernel compiles the Kernel and that you experience random freezes from the whole server Kernel Panics or even the driver not working properly or not working at all.

The second way is to compile your own driver for this Kernel version but that can get tedious and time consuming pretty quick.


> Guide on changing kernels

I know, I do such things very often and compile my own Kernels.

But nowadays I don't recommend custom Kernels because these can have various backdoors and so on (but I don't think that this is the case for the linked Kernel, but it is always a thing to keep in mind).


> If it is out of scope feel free to close it, LimeTech will eventually update the kernel but it's probably in a couple of months.

A new beta could be drop more soon than you think, as you might know as a developer there can be many road blocks which prevents a release to the public or even beta.


Hope that helps and explains a bit more, if you have further questions feel free to ask or if this explains everything please close this issue.

**Comment by ich777** [comment]
@BGameiro2000 closing this issue due to no response. If you have any further questions feel free to reopen the issue or create a new issue.
